allWords = [
  // VOEDSEL
  {jp:"りんご",nl:"appel",romaji:"ringo",cat:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"みかん",nl:"sinaasappel",romaji:"mikan",cat:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"ぶどう",nl:"druif",romaji:"budou",cat:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"もも",nl:"perzik",romaji:"momo",cat:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"いちご",nl:"aardbei",romaji:"ichigo",cat:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"きゅうり",nl:"komkommer",romaji:"kyuuri",cat:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"にんじん",nl:"wortel",romaji:"ninjin",cat:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"じゃがいも",nl:"aardappel",romaji:"jagaimo",cat:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"たまねぎ",nl:"ui",romaji:"tamanegi",cat:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"にんにく",nl:"knoflook",romaji:"ninniku",cat:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"ぎゅうにく",nl:"rundvlees",romaji:"gyuuniku",cat:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"ぶtaにく",nl:"varkensvlees",romaji:"butaniku",cat:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"とりにく",nl:"kippenvlees",romaji:"toriniku",cat:"voedsel",taal:"hiragana",hoofdklank:""},
  {jp:"さつまいも",nl:"zoete aardappel",romaji:"satsumaimo",cat:"voedsel",taal:"hiragana",hoofdklank:""},

  // FAMILIE
  {jp:"おかあさん",nl:"moeder",romaji:"okaasan",cat:"familie",taal:"hiragana",hoofdklank:""},
  {jp:"おとうさん",nl:"vader",romaji:"otoosan",cat:"familie",taal:"hiragana",hoofdklank:""},
  {jp:"おねえさん",nl:"oudere zus",romaji:"oneesan",cat:"familie",taal:"hiragana",hoofdklank:""},
  {jp:"おにいさん",nl:"oudere broer",romaji:"oniisan",cat:"familie",taal:"hiragana",hoofdklank:""},
  {jp:"いもうと",nl:"jonger zusje",romaji:"imooto",cat:"familie",taal:"hiragana",hoofdklank:""},
  {jp:"おとうと",nl:"jonger broertje",romaji:"otooto",cat:"familie",taal:"hiragana",hoofdklank:""},

  // LICHAAM
  {jp:"けんこう",nl:"gezondheid",romaji:"kenkou",cat:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"は",nl:"gebit",romaji:"ha",cat:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"くち",nl:"mond",romaji:"kuchi",cat:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"のど",nl:"keel",romaji:"nodo",cat:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"せなか",nl:"rug",romaji:"senaka",cat:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"ひざ",nl:"knie",romaji:"hiza",cat:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"かた",nl:"schouder",romaji:"kata",cat:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"はな",nl:"neus",romaji:"hana",cat:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"くび",nl:"nek",romaji:"kubi",cat:"lichaam",taal:"hiragana",hoofdklank:""},
  {jp:"こころ",nl:"geest",romaji:"kokoro",cat:"lichaam",taal:"hiragana",hoofdklank:""},

  // EMOTIE
  {jp:"よろこび",nl:"plezier",romaji:"yorokobi",cat:"emotie",taal:"hiragana",hoofdklank:""},
  {jp:"あんしん",nl:"gerust",romaji:"anshin",cat:"emotie",taal:"hiragana",hoofdklank:""},
  {jp:"おこる",nl:"boos",romaji:"okoru",cat:"emotie",taal:"hiragana",hoofdklank:""},
  {jp:"はずかしい",nl:"verlegen",romaji:"hazukashii",cat:"emotie",taal:"hiragana",hoofdklank:""},
  {jp:"ゆうき",nl:"moed",romaji:"yuuki",cat:"emotie",taal:"hiragana",hoofdklank:""},

  // CULTUUR
  {jp:"ともだち",nl:"vriend",romaji:"tomodachi",cat:"cultuur",taal:"hiragana",hoofdklank:""},
  {jp:"かぞく",nl:"gezin",romaji:"kazoku",cat:"cultuur",taal:"hiragana",hoofdklank:""},
  {jp:"じんじゃ",nl:"shrine",romaji:"jinja",cat:"cultuur",taal:"hiragana",hoofdklank:""},
  {jp:"おてら",nl:"temple",romaji:"otera",cat:"cultuur",taal:"hiragana",hoofdklank:""},
  {jp:"ぶんか",nl:"cultuur",romaji:"bunka",cat:"cultuur",taal:"hiragana",hoofdklank:""},
  {jp:"えいが",nl:"film",romaji:"eiga",cat:"cultuur",taal:"hiragana",hoofdklank:""},
  {jp:"うつくしい",nl:"schoon",romaji:"utsukushii",cat:"cultuur",taal:"hiragana",hoofdklank:""},

  // SCHOOL
  {jp:"せんせい",nl:"leraar",romaji:"sensei",cat:"school",taal:"hiragana",hoofdklank:""},
  {jp:"こうこう",nl:"high school",romaji:"kookoo",cat:"school",taal:"hiragana",hoofdklank:""},
  {jp:"じゅぎょう",nl:"les",romaji:"jugyou",cat:"school",taal:"hiragana",hoofdklank:""},
  {jp:"しけん",nl:"examen",romaji:"shiken",cat:"school",taal:"hiragana",hoofdklank:""},
  {jp:"としょかん",nl:"bibliotheek",romaji:"toshokan",cat:"school",taal:"hiragana",hoofdklank:""},
  {jp:"かがく",nl:"scheikunde",romaji:"kagaku",cat:"school",taal:"hiragana",hoofdklank:""},
  {jp:"すうがく",nl:"wiskunde",romaji:"suugaku",cat:"school",taal:"hiragana",hoofdklank:""},
  {jp:"にほんご",nl:"Japanse taal",romaji:"nihongo",cat:"school",taal:"hiragana",hoofdklank:""},
  {jp:"だいがく",nl:"universiteit",romaji:"daigaku",cat:"school",taal:"hiragana",hoofdklank:""},
  {jp:"がくせい",nl:"student",romaji:"gakusee",cat:"school",taal:"hiragana",hoofdklank:""},
  {jp:"だいがくせい",nl:"universiteits student",romaji:"daigakusee",cat:"school",taal:"hiragana",hoofdklank:""},
  {jp:"せんこう",nl:"master",romaji:"senkoo",cat:"school",taal:"hiragana",hoofdklank:""},

  // NATUUR
  {jp:"やま",nl:"berg",romaji:"yama",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"もり",nl:"bos",romaji:"mori",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"かわ",nl:"rivier",romaji:"kawa",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"うみ",nl:"zee",romaji:"umi",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"そら",nl:"lucht",romaji:"sora",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"たいよう",nl:"zon",romaji:"taiyou",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"つき",nl:"maan",romaji:"tsuki",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"ほし",nl:"ster",romaji:"hoshi",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"あめ",nl:"regen",romaji:"ame",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"ゆき",nl:"sneeuw",romaji:"yuki",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"かぜ",nl:"wind",romaji:"kaze",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"はな",nl:"flower",romaji:"hana",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"き",nl:"boom",romaji:"ki",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"いけ",nl:"vijver",romaji:"ike",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"むし",nl:"insect",romaji:"mushi",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"とり",nl:"vogel",romaji:"tori",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"さる",nl:"aap",romaji:"saru",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"うし",nl:"koe",romaji:"ushi",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"ねこ",nl:"kat",romaji:"neko",cat:"natuur",taal:"hiragana",hoofdklank:""},
  {jp:"いぬ",nl:"hond",romaji:"inu",cat:"natuur",taal:"hiragana",hoofdklank:""},

  // TRANSPORT
  {jp:"クルマ",nl:"auto",romaji:"kuruma",cat:"transport",taal:"katakana",hoofdklank:""},
  {jp:"じてんしゃ",nl:"fiets",romaji:"jitensha",cat:"transport",taal:"hiragana",hoofdklank:""},
  {jp:"でんしゃ",nl:"trein",romaji:"densha",cat:"transport",taal:"hiragana",hoofdklank:""},
  {jp:"ヒコウキ",nl:"vliegtuig",romaji:"hikouki",cat:"transport",taal:"katakana",hoofdklank:""},
  {jp:"ふね",nl:"boot",romaji:"fune",cat:"transport",taal:"hiragana",hoofdklank:""},
  {jp:"バス",nl:"bus",romaji:"basu",cat:"transport",taal:"katakana",hoofdklank:""},

  // KLEDING
  {jp:"くつ",nl:"schoenen",romaji:"kutsu",cat:"kleding",taal:"hiragana",hoofdklank:""},
  {jp:"ふく",nl:"kleding",romaji:"fuku",cat:"kleding",taal:"hiragana",hoofdklank:""},
  {jp:"ぼうし",nl:"hoed",romaji:"boushi",cat:"kleding",taal:"hiragana",hoofdklank:""},
  {jp:"てぶくろ",nl:"handschoenen",romaji:"tebukuro",cat:"kleding",taal:"hiragana",hoofdklank:""},
  {jp:"マフラー",nl:"sjaal",romaji:"mafuraa",cat:"kleding",taal:"katakana",hoofdklank:""},
  {jp:"スカート",nl:"rok",romaji:"sukaato",cat:"kleding",taal:"katakana",hoofdklank:""},
  {jp:"シャツ",nl:"shirt",romaji:"shatsu",cat:"kleding",taal:"katakana",hoofdklank:""},
  {jp:"ズボン",nl:"broek",romaji:"zubon",cat:"kleding",taal:"katakana",hoofdklank:""},
  {jp:"ワンピース",nl:"jurk",romaji:"wanpiisu",cat:"kleding",taal:"katakana",hoofdklank:""},
  {jp:"くびわ",nl:"ketting",romaji:"kubiwa",cat:"kleding",taal:"hiragana",hoofdklank:""},

  // OVERIG
  {jp:"かさ",nl:"paraplu",romaji:"kasa",cat:"overig",taal:"hiragana",hoofdklank:""},
  {jp:"めがね",nl:"bril",romaji:"megane",cat:"overig",taal:"hiragana",hoofdklank:""},
  {jp:"けいたい",nl:"telefoon",romaji:"keitai",cat:"overig",taal:"hiragana",hoofdklank:""},
  {jp:"でんき",nl:"licht",romaji:"denki",cat:"overig",taal:"hiragana",hoofdklank:""},
  {jp:"がっき",nl:"muziekinstrument",romaji:"gakki",cat:"overig",taal:"hiragana",hoofdklank:""},
  {jp:"ピアノ",nl:"piano",romaji:"piano",cat:"overig",taal:"katakana",hoofdklank:""},
  {jp:"バイオリン",nl:"viool",romaji:"baiorin",cat:"overig",taal:"katakana",hoofdklank:""},

  // SPORT
  {jp:"サッカー",nl:"voetbal",romaji:"sakkaa",cat:"sport",taal:"katakana",hoofdklank:""},
  {jp:"やきゅう",nl:"honkbal",romaji:"yakyuu",cat:"sport",taal:"hiragana",hoofdklank:""},
  {jp:"バスケット",nl:"basketbal",romaji:"basuketto",cat:"sport",taal:"katakana",hoofdklank:""},
  {jp:"すいえい",nl:"zwemmen",romaji:"sui-ei",cat:"sport",taal:"hiragana",hoofdklank:""},
  {jp:"テニス",nl:"tennis",romaji:"tenisu",cat:"sport",taal:"katakana",hoofdklank:""},
  {jp:"ジョギング",nl:"joggen",romaji:"jogingu",cat:"sport",taal:"katakana",hoofdklank:""},
  {jp:"ランニング",nl:"running",romaji:"ranningu",cat:"sport",taal:"katakana",hoofdklank:""},

  // LITERATUUR
  {jp:"え",nl:"tekening",romaji:"e",cat:"literatuur",taal:"hiragana",hoofdklank:""},

  // GROETEN
  {jp:"ありがとうございます",nl:"dankuwel",romaji:"arigatou gozaimasu",cat:"groeten",taal:"hiragana",hoofdklank:""},
  {jp:"こんにちは",nl:"hallo",romaji:"konnichiwa",cat:"groeten",taal:"hiragana",hoofdklank:""},
  {jp:"おはようございます",nl:"goedemorgen",romaji:"ohayou gozaimasu",cat:"groeten",taal:"hiragana",hoofdklank:""},
  {jp:"すみません",nl:"pardon",romaji:"sumimasen",cat:"groeten",taal:"hiragana",hoofdklank:""},
  {jp:"ごめんなさい",nl:"sorry",romaji:"gomennasai",cat:"groeten",taal:"hiragana",hoofdklank:""},
  {jp:"はい",nl:"ja",romaji:"hai",cat:"groeten",taal:"hiragana",hoofdklank:""},
  {jp:"はじめまして",nl:"leuk om je te ontmoeten",romaji:"hajimemashite",cat:"groeten",taal:"hiragana",hoofdklank:""},

  // TIJD
  {jp:"きょう",nl:"vandaag",romaji:"kyou",cat:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"きのう",nl:"gisteren",romaji:"kinou",cat:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"あした",nl:"morgen",romaji:"ashita",cat:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"しゅう",nl:"week",romaji:"shuu",cat:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"とし",nl:"jaar",romaji:"toshi",cat:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"びょう",nl:"seconde",romaji:"byou",cat:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"いま",nl:"nu",romaji:"ima",cat:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"ごぜん",nl:"00.00-12.00",romaji:"gozen",cat:"tijd",taal:"hiragana",hoofdklank:""},
  {jp:"ごご",nl:"12.00-00.00",romaji:"gogo",cat:"tijd",taal:"hiragana",hoofdklank:""},

  // HIRAGANA ALFABET
  {jp:"あ",nl:"a",romaji:"a",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"a"},
  {jp:"い",nl:"i",romaji:"i",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"a"},
  {jp:"う",nl:"u",romaji:"u",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"a"},
  {jp:"え",nl:"e",romaji:"e",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"a"},
  {jp:"お",nl:"o",romaji:"o",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"a"},
  {jp:"か",nl:"ka",romaji:"ka",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"き",nl:"ki",romaji:"ki",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"く",nl:"ku",romaji:"ku",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"け",nl:"ke",romaji:"ke",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"こ",nl:"ko",romaji:"ko",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"さ",nl:"sa",romaji:"sa",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"し",nl:"shi",romaji:"shi",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"a"},
  {jp:"す",nl:"su",romaji:"su",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"せ",nl:"se",romaji:"se",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"そ",nl:"so",romaji:"so",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"た",nl:"ta",romaji:"ta",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"ち",nl:"chi",romaji:"chi",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"つ",nl:"tsu",romaji:"tsu",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"て",nl:"te",romaji:"te",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"と",nl:"to",romaji:"to",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"な",nl:"na",romaji:"na",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"na"},
  {jp:"に",nl:"ni",romaji:"ni",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"na"},
  {jp:"ぬ",nl:"nu",romaji:"nu",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"na"},
  {jp:"ね",nl:"ne",romaji:"ne",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"na"},
  {jp:"の",nl:"no",romaji:"no",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"na"},
  {jp:"は",nl:"ha",romaji:"ha",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ひ",nl:"hi",romaji:"hi",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ふ",nl:"fu",romaji:"fu",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"へ",nl:"he",romaji:"he",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ほ",nl:"ho",romaji:"ho",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ま",nl:"ma",romaji:"ma",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ma"},
  {jp:"み",nl:"mi",romaji:"mi",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ma"},
  {jp:"む",nl:"mu",romaji:"mu",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ma"},
  {jp:"め",nl:"me",romaji:"me",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ma"},
  {jp:"も",nl:"mo",romaji:"mo",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ma"},
  {jp:"や",nl:"ya",romaji:"ya",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ya"},
  {jp:"ゆ",nl:"yu",romaji:"yu",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ya"},
  {jp:"よ",nl:"yo",romaji:"yo",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ya"},
  {jp:"ら",nl:"ra",romaji:"ra",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ra"},
  {jp:"り",nl:"ri",romaji:"ri",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ra"},
  {jp:"る",nl:"ru",romaji:"ru",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ra"},
  {jp:"れ",nl:"re",romaji:"re",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ra"},
  {jp:"ろ",nl:"ro",romaji:"ro",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ra"},
  {jp:"わ",nl:"wa",romaji:"wa",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"wa"},
  {jp:"を",nl:"wo",romaji:"wo",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"wa"},
  {jp:"ん",nl:"n",romaji:"n",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"wa"},

  // KATAKANA ALFABET
  {jp:"ア",nl:"a",romaji:"a",cat:"katakana alfabet",taal:"katakana",hoofdklank:"a"},
  {jp:"イ",nl:"i",romaji:"i",cat:"katakana alfabet",taal:"katakana",hoofdklank:"a"},
  {jp:"ウ",nl:"u",romaji:"u",cat:"katakana alfabet",taal:"katakana",hoofdklank:"a"},
  {jp:"エ",nl:"e",romaji:"e",cat:"katakana alfabet",taal:"katakana",hoofdklank:"a"},
  {jp:"オ",nl:"o",romaji:"o",cat:"katakana alfabet",taal:"katakana",hoofdklank:"a"},
  {jp:"カ",nl:"ka",romaji:"ka",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"キ",nl:"ki",romaji:"ki",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"ク",nl:"ku",romaji:"ku",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"ケ",nl:"ke",romaji:"ke",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"コ",nl:"ko",romaji:"ko",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"サ",nl:"sa",romaji:"sa",cat:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"シ",nl:"shi",romaji:"shi",cat:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"ス",nl:"su",romaji:"su",cat:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"セ",nl:"se",romaji:"se",cat:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"ソ",nl:"so",romaji:"so",cat:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"タ",nl:"ta",romaji:"ta",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"チ",nl:"chi",romaji:"chi",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"ツ",nl:"tsu",romaji:"tsu",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"テ",nl:"te",romaji:"te",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"ト",nl:"to",romaji:"to",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"ナ",nl:"na",romaji:"na",cat:"katakana alfabet",taal:"katakana",hoofdklank:"na"},
  {jp:"ニ",nl:"ni",romaji:"ni",cat:"katakana alfabet",taal:"katakana",hoofdklank:"na"},
  {jp:"ヌ",nl:"nu",romaji:"nu",cat:"katakana alfabet",taal:"katakana",hoofdklank:"na"},
  {jp:"ネ",nl:"ne",romaji:"ne",cat:"katakana alfabet",taal:"katakana",hoofdklank:"na"},
  {jp:"ノ",nl:"no",romaji:"no",cat:"katakana alfabet",taal:"katakana",hoofdklank:"na"},
  {jp:"ハ",nl:"ha",romaji:"ha",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ヒ",nl:"hi",romaji:"hi",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"フ",nl:"fu",romaji:"fu",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ヘ",nl:"he",romaji:"he",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ホ",nl:"ho",romaji:"ho",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"マ",nl:"ma",romaji:"ma",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ma"},
  {jp:"ミ",nl:"mi",romaji:"mi",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ma"},
  {jp:"ム",nl:"mu",romaji:"mu",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ma"},
  {jp:"メ",nl:"me",romaji:"me",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ma"},
  {jp:"モ",nl:"mo",romaji:"mo",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ma"},
  {jp:"ヤ",nl:"ya",romaji:"ya",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ya"},
  {jp:"ユ",nl:"yu",romaji:"yu",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ya"},
  {jp:"ヨ",nl:"yo",romaji:"yo",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ya"},
  {jp:"ラ",nl:"ra",romaji:"ra",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ra"},
  {jp:"リ",nl:"ri",romaji:"ri",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ra"},
  {jp:"ル",nl:"ru",romaji:"ru",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ra"},
  {jp:"レ",nl:"re",romaji:"re",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ra"},
  {jp:"ロ",nl:"ro",romaji:"ro",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ra"},
  {jp:"ワ",nl:"wa",romaji:"wa",cat:"katakana alfabet",taal:"katakana",hoofdklank:"wa"},
  {jp:"ヲ",nl:"wo",romaji:"wo",cat:"katakana alfabet",taal:"katakana",hoofdklank:"wa"},
  {jp:"ン",nl:"n",romaji:"n",cat:"katakana alfabet",taal:"katakana",hoofdklank:"wa"},

  // DAKUTEN HIRAGANA
  {jp:"が",nl:"ga",romaji:"ga",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"ぎ",nl:"gi",romaji:"gi",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"ぐ",nl:"gu",romaji:"gu",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"げ",nl:"ge",romaji:"ge",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"ご",nl:"go",romaji:"go",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ka"},
  {jp:"ざ",nl:"za",romaji:"za",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"じ",nl:"ji",romaji:"ji",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"ず",nl:"zu",romaji:"zu",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"ぜ",nl:"ze",romaji:"ze",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"ぞ",nl:"zo",romaji:"zo",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"sa"},
  {jp:"だ",nl:"da",romaji:"da",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"ぢ",nl:"ji",romaji:"ji",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"づ",nl:"zu",romaji:"zu",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"で",nl:"de",romaji:"de",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"ど",nl:"do",romaji:"do",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ta"},
  {jp:"ば",nl:"ba",romaji:"ba",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"び",nl:"bi",romaji:"bi",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ぶ",nl:"bu",romaji:"bu",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"べ",nl:"be",romaji:"be",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ぼ",nl:"bo",romaji:"bo",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ぱ",nl:"pa",romaji:"pa",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ぴ",nl:"pi",romaji:"pi",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ぷ",nl:"pu",romaji:"pu",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ぺ",nl:"pe",romaji:"pe",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},
  {jp:"ぽ",nl:"po",romaji:"po",cat:"hiragana alfabet",taal:"hiragana",hoofdklank:"ha"},

  // DAKUTEN KATAKANA
  {jp:"ガ",nl:"ga",romaji:"ga",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"ギ",nl:"gi",romaji:"gi",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"グ",nl:"gu",romaji:"gu",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"ゲ",nl:"ge",romaji:"ge",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"ゴ",nl:"go",romaji:"go",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ka"},
  {jp:"ザ",nl:"za",romaji:"za",cat:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"ジ",nl:"ji",romaji:"ji",cat:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"ズ",nl:"zu",romaji:"zu",cat:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"ゼ",nl:"ze",romaji:"ze",cat:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"ゾ",nl:"zo",romaji:"zo",cat:"katakana alfabet",taal:"katakana",hoofdklank:"sa"},
  {jp:"ダ",nl:"da",romaji:"da",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"ヂ",nl:"ji",romaji:"ji",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"ヅ",nl:"zu",romaji:"zu",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"デ",nl:"de",romaji:"de",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"ド",nl:"do",romaji:"do",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ta"},
  {jp:"バ",nl:"ba",romaji:"ba",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ビ",nl:"bi",romaji:"bi",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ブ",nl:"bu",romaji:"bu",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ベ",nl:"be",romaji:"be",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ボ",nl:"bo",romaji:"bo",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"パ",nl:"pa",romaji:"pa",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ピ",nl:"pi",romaji:"pi",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"プ",nl:"pu",romaji:"pu",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ペ",nl:"pe",romaji:"pe",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"},
  {jp:"ポ",nl:"po",romaji:"po",cat:"katakana alfabet",taal:"katakana",hoofdklank:"ha"}
];
